<a href="https://colab.research.google.com/github/justoneye/Bootcamp-IA-G84/blob/main/Unidad7_Sesion2_Variable_Operadores_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://drive.google.com/uc?id=1nptVTliqyIIOzwF08JXJkWEvlYUC4_g5'  width="1500" height="300">

<div class="markdown-google-sans">
  <h1>Operadores en Python</h1>
</div>

Python admite los operadores aritméticos habituales:
+ (suma), * (multiplicación), / (división),  ** (potencia), // (división de enteros), entre otros.

<div class="markdown-google-sans">
  <h1>Ejercicio 1</h1>
</div>

In [3]:
# Elevar a la potencia array_b el array_a (array_a)^array_b

import numpy as np

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

b2 = array_b ** 2
display(b2)
a2 = array_a ** array_b
display(a2)

array([16, 25, 36])

array([  1,  32, 729])

<div class="markdown-google-sans">
  <h1>Ejercicio 2</h1>
</div>

In [ ]:
# Ordenar los elementos del array_a de menor a mayor para obtener el
# array_ordenado = np.array([[-4, -2, 1],[3, 5, 6]])
import numpy as np
array_a = np.array([[-4, 5, 6],[1, -2, 3]])

<div class="markdown-google-sans">
  <h1>Ejercicio 3</h1>
</div>

In [ ]:
# Ordenar los elementos del array_a de menor a mayor para obtener el
# array_ordenado = np.array([[-4, -2, 1],[3, 5, 6]])
import numpy as np
array_a = np.array([[-4, 5, 6],[1, -2, 3]])
array_a

array([[-4,  5,  6],
       [ 1, -2,  3]])

<div class="markdown-google-sans">
  <h1>Ejercicio 4</h1>
</div>

In [ ]:
# Calcular el volumen de un cilindro con altura de 10cm, y diametro de 16cm. Compare su resultado en el siguiente link: https://www.omnicalculator.com/es/matematicas/volumen-de-cilindro
# Nota: Usar el número pi que tiene Python con todas las cifras, NO aproximar a 3,159 ni a 31,14!

<div class="markdown-google-sans">
  <h1>Ejercicio 5</h1>
</div>

In [ ]:
# El indice de masa corporal de una persona se calcula como: IMC = Peso (en Kg) / Estatura  al cuadrado (en metros).
# https://www.minsalud.gov.co/salud/Paginas/Evalue-su-peso.aspx
# Crear un vector con los pesos de 5 personas y otro vector con las 5 estaturas, calcular el IMC

<div class="markdown-google-sans">
  <h1>Ejercicio 6</h1>
</div>

In [ ]:
meses_1 = ["Enero", "Febrero", "Diciembre", "Abril", "Mayo"]
# 1. Actualizar el tercer mes de 'meses_1'
# 2. Crear otro array 'meses_2' con los meses faltantes
# 3. Concatenar los 2 arrays y crear un nuevo array con todos los meses del año

<img src='https://drive.google.com/uc?id=1JTvS_vjZTzQfHiMOt9ZbfqmjNN1FvOOm'>