<a href="https://colab.research.google.com/github/justoneye/Bootcamp-IA-G84/blob/main/Unidad7_Sesion1_PrimerScriptPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://drive.google.com/uc?id=1nptVTliqyIIOzwF08JXJkWEvlYUC4_g5'  width="1500" height="300">

<div class="markdown-google-sans">
  <h1>Python</h1>
</div>

Python es uno de los lenguajes de programación más populares para realizar aplicaciones basadas en Inteligencia Artificial, tanto en el ámbito académico como en la industria. Por ello, resulta esencial aprender este lenguaje para cualquier persona interesada en Inteligencia Artificial. En esta Notebook, repasaremos los conceptos básicos de Python.

# NumPy

NumPy es la biblioteca más popular de Python y sirve para almacenar vectores y matrices de números para poder realizar cálculos con ellas. Esto no solo permite escribir código a menudo más conciso, sino que también hace que el código sea más rápido, ya que la mayoría de las rutinas de NumPy se implementan en C para mayor velocidad.

In [10]:
# Debemos importar Numpy antes de poder usarla
import numpy as np

In [2]:
# Para crear un vector y una matriz se debe usar np.array a una lista
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2, 3],[4, 5, 6]])
vector, matriz

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [3]:
# Buscando el elemnto con posición fila= 1, columna=2
matriz[1, 2]

np.int64(6)

In [4]:
matriz[1]

array([4, 5, 6])

In [5]:
matriz[:, 2]

array([3, 6])

In [6]:
# Dimension del "array"
print(vector.ndim)
print(matriz.ndim)

1
2


In [7]:
# Tamaño del "array"
print(vector.shape)
print(matriz.shape)

(3,)
(2, 3)


In [16]:
# El tipo de datos del "array"
vector.dtype, matriz.dtype

(dtype('int64'), dtype('int64'))

<div class="markdown-google-sans">
  <h1>Ejercicio 1</h1>
</div>

In [27]:
# Crear un array con dim=2, shape=(5,5) y dtype='np.int64'
# Escriba su código acá

import numpy as np

arreglo = np.array([[2, 8, 20, 24, 4],[7, 17, 43, 31, 23],[12, 50, 44, 43, 17],[12, 24, 20, 7, 27],[12, 28, 18, 27, 43]])
print("Dimensión:", arreglo.ndim, "\nShape:", arreglo.shape, "\nTipo: ", arreglo.dtype)

Dimensión: 2 
Shape: (5, 5) 
Tipo:  int64


In [28]:
# Creando "array" con todos los elementos en 0
ceros = np.zeros((2, 3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# Creando "array" con todos los elementos en 1
unos = np.ones((2, 3))
unos

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# Creando "array" con todos los elementos en forma ascedente
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
# Creando "array" con todos los elementos en un rango
np.arange(3, 7)

array([3, 4, 5, 6])

<div class="markdown-google-sans">
  <h1>Ejercicio 2</h1>
</div>

In [50]:
# Crear un array de 4x3 y usar .reshape para generar: un array de 3x4 y otro array de 6x2

import numpy as np

arreglo = np.array([[2, 20, 24],[7, 17, 23],[12, 18, 43],[18, 23, 43]])
print("\nArreglo:\n", arreglo, "\nShape:", arreglo.shape)

nuevoArreglo = arreglo.reshape(3, 4)
print("\nNuevo Arreglo:\n", nuevoArreglo, "\nShape:", nuevoArreglo.shape)


# Métodos 2: Números al azar

from numpy import random

print("\n\nMétodos 2: Números al azar ----------")

arregloRandom = random.randint(50, size=(4, 3))
print("\nArreglo Random:\n", arregloRandom, "\nShape:", arregloRandom.shape)

nuevoRandom = arregloRandom.reshape(3, 4)
print("\nNuevo Random:\n", nuevoRandom, "\nShape:", nuevoRandom.shape)


Arreglo:
 [[ 2 20 24]
 [ 7 17 23]
 [12 18 43]
 [18 23 43]] 
Shape: (4, 3)

Nuevo Arreglo:
 [[ 2 20 24  7]
 [17 23 12 18]
 [43 18 23 43]] 
Shape: (3, 4)


Métodos 2: Números al azar ----------

Arreglo Random:
 [[ 0 48 24]
 [30  1 41]
 [47  8  0]
 [ 3 43 40]] 
Shape: (4, 3)

Nuevo Random:
 [[ 0 48 24 30]
 [ 1 41 47  8]
 [ 0  3 43 40]] 
Shape: (3, 4)


In [75]:
# Crear una lista de la estatura de n personas.

import numpy as np

listaEstaturas = []
personas = int(input("Cuántas personas van a añadir a lista?: "))

for i in range(personas):
  estatura = float(input(" - Ingrese estatura: "))
  listaEstaturas.append(estatura);

arrayLista = np.array(listaEstaturas)

print("\n Media:", arrayLista.mean())

Cuántas personas van a añadir a lista?: 5
 - Ingrese estatura: 1.23
 - Ingrese estatura: 1.25
 - Ingrese estatura: 1.20
 - Ingrese estatura: 1.24
 - Ingrese estatura: 1.4

 Media: 1.264


<div class="markdown-google-sans">
  <h1>Ejercicio 3</h1>
</div>

In [65]:
# Crear un array con elementos ascedentes desde el 10 hasta el 100, y presentar los 30 valores intermedios

import numpy as np

arreglo = np.full((30), 10)
print("\nArreglo:\n", arreglo)


Arreglo:
 [10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10]


<div class="markdown-google-sans">
  <h1>Ejercicio 4</h1>
</div>

In [ ]:
# Crear un 3d array (dim=3) con tamaño (2,2,2) que contenga 8 valores. Acceder a cada uno de los elementos individuales y por filas y columnas

<div class="markdown-google-sans">
  <h1>Ejercicio 5</h1>
</div>

In [ ]:
# Defina el siguiente arreglo y calcule la media. Media es la suma de los elementos dividido por el número de elementos
np.arange(3, 6)

array([3, 4, 5])

<div class="markdown-google-sans">
  <h1>Ejercicio 6</h1>
</div>

In [ ]:
# Defina el siguiente arreglo y genere un nuevo array que contenga cada uno de sus elementos elevado al cubo
array = np.array([[1, 2, 3],[4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

<div class="markdown-google-sans">
  <h1>Ejercicio 7</h1>
</div>

In [ ]:
# Calcule la norma euclidiana del siguiente vector (ver siguiente https://es.wikipedia.org/wiki/Norma_vectorial)
np.array([0.5, -1.2, 3.3, 4.5])

array([ 0.5, -1.2,  3.3,  4.5])

<div class="markdown-google-sans">
  <h1>Ejercicio 8</h1>
</div>

In [ ]:
# Calcule la norma euclidiana del siguiente 2d array (ver siguiente https://es.wikipedia.org/wiki/Norma_vectorial)
np.array([[0.5, -1.2, 4.5],
          [-3.2, 1.9, 2.7]])

array([[ 0.5, -1.2,  4.5],
       [-3.2,  1.9,  2.7]])

* [NumPy](https://numpy.org/doc/stable/reference/)
* [SciPy](https://scipy-lectures.org/)
* Youtube [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI)



<img src='https://drive.google.com/uc?id=1JTvS_vjZTzQfHiMOt9ZbfqmjNN1FvOOm'>